name: dc_datatable_paginator
description: Widget Datatable with pagination
version: 1.0.3
homepage: https://github.com/ddbits/dc_datatable.git


environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
